import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/ui/Navbar";
import { auth } from "@/lib/auth";
import { SessionProvider } from "next-auth/react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <Navbar />
          <ToastContainer />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
